apiVersion: v2
name: openldap-stack-ha
dependencies:
  - name: ltb-passwd
    version: 0.1.x
    condition: ltb-passwd.enabled
  - name: phpldapadmin
    version: 0.1.x
    condition: phpldapadmin.enabled
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://www.openldap.org
version: 3.1.0
appVersion: 2.4.57
description: Community developed LDAP software
icon: https://raw.githubusercontent.com/dpsi4/helm-openldap/master/logo.png
keywords:
  - ldap
  - openldap
  - iam-stack
  - high availability 
sources:
  - https://github.com/dpsi4/helm-openldap
maintainers:
  - name: Reid Miller
    email: reidm@dpsi4.net
engine: gotpl
