apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-failure-openldap
  namespace: openldap-pipeline
spec:
  action: pod-failure
  mode: random-max-percent
  value: 100
  duration: "15s"
  selector:
    labelSelectors:
      "app.kubernetes.io/app": "openldap-pipeline"
  scheduler:
    cron: "@every 2m"