# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPhpldap():

  def setup_method(self, method):
    op = webdriver.ChromeOptions()
    op.add_argument('headless')
    self.driver = webdriver.Chrome(options=op)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_phpldap(self):
    self.driver.get("http://phpldapadmin.example.lan:8080/")
    print(self.driver.title)
    self.driver.find_element(By.LINK_TEXT, "login").click()
    #element = self.driver.find_element(By.LINK_TEXT, "login")
    #actions = ActionChains(self.driver)
    #actions.move_to_element(element).perform()
    #element = self.driver.find_element(By.CSS_SELECTOR, "body")
    #actions = ActionChains(self.driver)
    #actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.ID, "login").click()
    self.driver.find_element(By.ID, "login").send_keys("cn=admin,dc=example,dc=org")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("admin")
    self.driver.find_element(By.NAME, "submit").click()
    print("successfully logged")
    #test = self.driver.find_element(By.XPATH, "//a[@href='cmd.php?cmd=template_engine&server_id=1&dn=dc%3Dexample%2Cdc%3Dorg']")
    #test.click()
    #main = test.find_element(By.XPATH, "//a[@title='dc=example,dc=org']")
    #print(main.find_element(By.XPATH, "//a[contains(text(), 'child')]"))
    #self.driver.find_element(By.ID, "posixAccount:2").click()
    #self.driver.find_element(By.ID, "new_values_givenname_0").click()
    #self.driver.find_element(By.ID, "new_values_givenname_0").send_keys("test")
    #self.driver.find_element(By.ID, "new_values_sn_0").send_keys("test")
    #self.driver.find_element(By.ID, "new_values_uid_0").click()
    #self.driver.find_element(By.ID, "new_values_userpassword_0").click()
    #self.driver.find_element(By.ID, "new_values_userpassword_0").send_keys("test")
    #self.driver.find_element(By.ID, "new_values_verify_userpassword_0").click()
    #self.driver.find_element(By.ID, "new_values_verify_userpassword_0").send_keys("test")
    #self.driver.find_element(By.ID, "new_values_gidnumber_0").click()
    #dropdown = self.driver.find_element(By.ID, "new_values_gidnumber_0")
    #dropdown.find_element(By.XPATH, "//option[. = 'myGroup']").click()
    #self.driver.find_element(By.ID, "create_button").click()
  
testClass = TestPhpldap()

testClass.setup_method("")
testClass.test_phpldap()
testClass.teardown_method("")
