{{- if (gt (.Values.readOnlyReplicaCount | int) 0) -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "openldap.fullname" . }}-headless-readonly
  labels:
    app.kubernetes.io/component: {{ template "openldap.fullname" . }}-readonly
    chart: {{ template "openldap.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  {{- if .Values.serviceReadOnly.enableLdapPort }}
  - port: {{ .Values.global.ldapPort }}
    name: ldap-port
    targetPort: ldap-port
  {{- end }}
  {{- if .Values.serviceReadOnly.enableSslLdapPort }}
  - port: {{ .Values.global.sslLdapPort }}
    name: ssl-ldap-port
    targetPort: ssl-ldap-port
  {{- end }}
  clusterIP: None
  selector:
    app.kubernetes.io/component: {{ template "openldap.fullname" . }}-readonly
    release: {{ .Release.Name }}  
  type: ClusterIP
  sessionAffinity: None
{{- end }}